### getGrandPrixWinners
GET http://localhost:3000/queries/grandPrixWinner HTTP/1.1

### getAllGrandChelems
GET http://localhost:3000/queries/grandChelem HTTP/1.1

### getGrandChelemDrivers
GET http://localhost:3000/queries/grandChelemDrivers HTTP/1.1

### getAllFastestLaps
GET http://localhost:3000/queries/fastestLap HTTP/1.1

### getPositionsGainedOrLosedPerGP
GET http://localhost:3000/queries/positionsGainedOrLosedPerGP HTTP/1.1

### getPositionsGainedOrLosedPerGPByDriverID
GET http://localhost:3000/queries/positionsGainedOrLosedPerGP/Leclerc HTTP/1.1

### getNeverReachedQ2
GET http://localhost:3000/queries/neverReached/Q2 HTTP/1.1

### getNeverReachedQ3
GET http://localhost:3000/queries/neverReached/Q3 HTTP/1.1

### qualifiedFirst
GET http://localhost:3000/queries/qualifiedFirst HTTP/1.1

### bestRacesOfDrivers
GET http://localhost:3000/queries/bestRacesOfDrivers HTTP/1.1

### bestRacesByDriverID
GET http://localhost:3000/queries/bestRaces/Leclerc HTTP/1.1

### worstRacesOfDrivers
GET http://localhost:3000/queries/worstRacesOfDrivers HTTP/1.1

### worstRacesByDriverID
GET http://localhost:3000/queries/worstRaces/Sainz HTTP/1.1

### allDriversAtPoints
GET http://localhost:3000/queries/allDriversAtPoints HTTP/1.1

### getDriversStandings
GET http://localhost:3000/queries/standings/drivers HTTP/1.1

### getTeamsStandings
GET http://localhost:3000/queries/standings/teams HTTP/1.1

### getDriversStandingsByGrandPrixID
GET http://localhost:3000/queries/standings/drivers/Imola HTTP/1.1

### getTeamsStandingsByGrandPrixID
GET http://localhost:3000/queries/standings/teams/Stavelot HTTP/1.1