### createDriver
POST http://localhost:3000/driver HTTP/1.1
Content-Type: application/json

{
  "firstName": "Alberto",
  "lastName": "Spinella",
  "shortName": "SPI",
  "number": 9,
  "nationality": "ita",
  "isFirstDriver": false,
  "age": 23,
  "worldTitles": 0
}

### getAllDrivers

GET http://localhost:3000/driver HTTP/1.1

### getDriver

GET http://localhost:3000/driver/Sainz HTTP/1.1

### deleteDriver

DELETE http://localhost:3000/driver/Leclerc HTTP/1.1